---
- hosts: all
  become_user: root
  become_method: sudo
  tasks:
    - name: "Ensure the apt cache is up to date"
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400  # 1 day
  roles:
    - role: env-common

- hosts: desktop
  become_user: root
  become_method: sudo
  roles:
    - role: env-desktop

- hosts: rfid_jukebox
  become_user: root
  become_method: sudo
  tags: rfid_jukebox
  roles:
    - role: rfid-jukebox
  tasks:
    - name: "Install packages to play audio files from the command line"
      become: true
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - sox
          - libsox-fmt-all
    - name: "Ensure /usr/local/share/sounds/rfid-jukebox/ exists"
      become: true
      file:
        path: /usr/local/share/sounds/rfid-jukebox/
        state: directory
    - name: "Copy audio file for notifications"
      become: true
      copy:
        src: /usr/share/sounds/Yaru/stereo/message-new-instant.oga
        dest: /usr/local/share/sounds/rfid-jukebox/yaru-message-new-instant.oga
    - name: "Copy audio files for notifications"
      become: true
      copy:
        src: files/sounds/
        dest: /usr/local/share/sounds/rfid-jukebox/
    - name: "Copy sound scripts for notifications"
      become: true
      template:
        src: "templates/{{ item }}.j2"
        dest: "/usr/local/share/sounds/rfid-jukebox/{{ item }}"
        mode: 0755
      loop:
        - one.sh
        - random.sh
    - name: "Ensure the rfid-jukebox user is in the audio group"
      become: true
      user:
        name: rfid-jukebox
        append: true
        groups: audio

- hosts: media_center
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast
      tags: snapcast
    - role: mopidy
      tags: mopidy
    - role: raspotify
      tags: raspotify

- hosts: media_player
  become_user: root
  become_method: sudo
  roles:
    - role: snapcast
      tags: snapcast

- hosts: raspberrypi
  become_user: root
  become_method: sudo
  tags: raspberrypi
  roles:
    - role: raspberrypi
