---
rfid_jukebox_version: "1.4.4"
rfid_jukebox_mopidy_base_url: "http://framboos:6680/mopidy/rpc"
rfid_jukebox_albums:
  "042abc4a325e81": "spotify:album:2WT1pbYjLJciAR26yMebkH"  # The Dark Side Of The Moon
  "0426bc4a325e81": "spotify:album:02Ast9sM8awNiA2ViVjO4Q"  # Nightfall in Middle Earth
  "042ebc4a325e81": "spotify:album:1YaUAkNsLKXtJfb0FVZcyu"  # New York - Addis - London
  "047cb07af36781": "http://icecast.omroep.nl/radio1-bb-mp3"  # NPO Radio 1
  "044bbb4a325e81": "spotify:album:0wKklfUh0GTGAICfuQxpMP"  # Bonga - Angola 72/74
  "0446bb4a325e81": "spotify:album:3DrgM5X3yX1JP1liNLAOHI"  # Arcade Fire - The Suburbs
  "0442bb4a325e81": "spotify:playlist:7klfbs5nEXp6KiVHcHcZXz"  # Feestselectie
  "043fbc4a325e81": "spotify:album:7EOQggjtK8JCqeRz9IG33e"  # Charles Mingus - Blues & Roots
  "043bbc4a325e81": "spotify:album:3ekjz97bhwf8OVWLGF46KM"  # Josh Garrels - Jacaranda
  "04b2b37af36780": "spotify:album:0GwClXkQ5pSjShjpWbPcrE"  # Charizma & Peanut Butter Wolf - Big Shots
  "04edb37af36780": "spotify:album:3S6qaM2ijmVtz68R6QMlPs"  # Johann Sebastian Bach - Bach: Violin Concertos
  "042ab37af36780": "spotify:album:3eZ9T4vXOtLpUQgWDA0nRG"  # Mensenkinderen - Wij leven van de wind
  "04ddb37af36780": "spotify:album:5xfPV8byJVCmeqe1LeVFqz"  # Guru - Jazzmatazz Volume II
  "04d4b37af36780": "spotify:album:7o9rYmsikfmzf2Z3mwSBNA"  # Rusko - Songs
  "0489b07af36780": "spotify:album:7u6zL7kqpgLPISZYXNTgYk"  # Daft Punk - Alive 2007
  "0481b07af36780": "spotify:playlist:3sAzPTdA6gIcHUYhw50912"  # I Like Sax
  "048cb07af36781": "spotify:album:0ZvyleSEIlDbklGZ995APl"  # GoGo Penguin - v2.0
  "0489b17af36781": "spotify:album:779P1LBXo4NylXQ0sHSKqT"  # GoGo Penguin - Fanfares
  "0442b17af36781": "spotify:album:7Eoz7hJvaX1eFkbpQxC5PA"  # John Coltrane - A Love Supreme
  "0471b07af36780": "spotify:album:3nLStxdTkSzihxm7FTLzCP"  # John Coltrane - My Favorite Things
  "0479b07af36780": "spotify:album:4A9NpSjSaA2cJss3ksEFVE"  # Moondog - Sax Pax For A Sax
  "04bcb27af36780": "http://www.ndr.de/resources/metadaten/audio/m3u/ndr2.m3u"  # NDR2
  "04b4b27af36780": "spotify:playlist:3Zswwtk7WLHFnOV84UFB68"  # Sharoni
  "04ceb27af36780": "spotify:playlist:09BN4BxxxlA4v4hQTQGPen"  # Christelijk
  "043ab17af36781": "spotify:album:4y83vqVrHDM6ZVK9oyOjhG"  # Mammal Hands - Animalia
  "04d6b27af36780": "spotify:album:2Ua7bVJnCpzcfqChuUBgZY"  # Mammal Hands - Floa
  "04deb27af36780": "spotify:album:6MQXgLKSXLb8SwZ4m7STNc"  # Beirut - Gulag Orkestar

rfid_jukebox_commands:
  "ebd1a421": "stop"  # Big chipcard
  "b02c3f32": "stop"  # Big chipcard
  "a98bbcb8": "shutdown"  # Blue transponder

rfid_jukebox_hooks:
  # "on-card-change": "bash -c 'sleep 0.25 && AUDIODEV=dmix:CARD=Device play -q /usr/local/share/sounds/rfid-jukebox/yaru-message-new-instant.oga -t alsa'"
  "on-initialize": "/usr/local/share/sounds/rfid-jukebox/random.sh on-initialize"
  "on-pause": "/usr/local/share/sounds/rfid-jukebox/one.sh yaru-message-new-instant.oga"
  "on-play": "/usr/local/share/sounds/rfid-jukebox/random.sh on-play"
  "on-resume": "/usr/local/share/sounds/rfid-jukebox/one.sh yaru-message-new-instant.oga"
  # "on-shutdown": "/usr/local/share/sounds/rfid-jukebox/random.sh on-shutdown"
  "on-stop": "/usr/local/share/sounds/rfid-jukebox/random.sh on-stop"

raspberrypi_audio_users:
  - pi
  - rfid-jukebox

sounds_delay: 0.2
